base:
  project: wine-quality-prediction
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.20

estimators:
  RandomForestRegressor:
    params:
      max_depth: 10
      min_samples_leaf: 2
      min_samples_split: 2
      n_estimators: 150
      # alpha: 0.5
      # l1_ratio: 0.4
      # alpha: 0.5
      # l1_ratio: 0.5

model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config: 
  artifacts_dir: artifacts
  experiment_name: RandomForest regression
  run_name: mlops
  registered_model_name: RandomForestWineModel
  remote_server_uri: http://127.0.0.1:1234



